print("Chào mừng bạn đến với trò chơi ai là triệu phú")
print("Trước tiên tôi sẽ nói cho bạn luật chơi: ")
print("Bạn phải trả lời 15 câu hỏi với mức độ từ dễ đến khó. Mỗi câu hỏi đều được gắn với một mức tiền thưởng cố định.")
print("Người chơi cần phải vượt qua 3 mốc quan trọng là ")
print("câu số 5, câu số 10 và câu số 15 mà khi vượt qua các mốc này, họ chắc chắn có được số tiền thưởng tương ứng của các câu hỏi đó.")
print("Bạn hãy cho tôi biết mục tiêu của bạn là bao nhiêu câu?")
nguoi=int(input())
print("Vậy thì chúng ta bắt đầu thôi nào")
print("Câu 1: (200.000 đồng) Loại vật nào sau đây không có răng?")
print("A. Dơi")
print("B. Mèo")
print("C. Bồ câu")
print("D. Ngựa")
nguoi1=input("Đáp án của bạn là: ")
if nguoi1 == "C":
    print("Bạn đã trả lời đúng")
    print("Số tiền hiện tại của bạn là 200.000 đồng")
else:
    print("Bạn trả lời sai rồi")
print("Câu 2: (200.000 đồng) Đâu là tên biểu tượng nổi tiếng ở New York, Mỹ?")
print("A. Tượng David")
print("B. Tượng thần vệ nữ")
print("C. Tượng nhân sư")
print("D. Tượng nữ thần tự do")
nguoi2=input("Đáp án của bạn là: ")
if nguoi2 == "D":
    print("Bạn đã trả lời đúng")
    print("Số tiền hiện tại của bạn là 400.000 đồng")
else:
    print("Bạn trả lời sai rồi")
print("Câu 3: (200.000 đồng) Nhân vật hoạt hình nào dưới đây là sư tử?")
print("A. Simba")
print("B. Micky")
print("C. Doraemon")
print("D. Donald")
nguoi3=input("Đáp án của bạn là: ")
if nguoi3 == "A":
    print("Bạn đã trả lời đúng")
    print("Số tiền hiện tại của bạn là 600.000 đồng")
else:
    print("Bạn trả lời sai rồi")
